# Generated by Django 5.0.3 on 2025-03-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/images/avatars/user-default.png', null=True, upload_to='static/images/avatars/'),
        ),
    ]
