# Generated by Django 5.0.3 on 2025-05-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_content_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_animated',
            field=models.BooleanField(default=False),
        ),
    ]
