# Generated by Django 5.0.3 on 2025-05-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_content_is_animated'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
