# Generated by Django 5.0.3 on 2025-05-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_content_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='source_stream_url',
            field=models.URLField(blank=True, help_text='Base m3u8 URL to parse', null=True),
        ),
    ]
