# Generated by Django 5.2.1 on 2025-06-01 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500)),
                ('voice_name', models.CharField(default='Невідоме озвучення', max_length=100)),
                ('data_id', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('streaming_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sources', to='movies.content')),
            ],
            options={
                'unique_together': {('content', 'source_url')},
            },
        ),
    ]
