# Generated by Django 5.2.1 on 2025-06-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_remove_content_source_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosource',
            name='quality',
            field=models.CharField(blank=True, default='Unknown', max_length=20),
        ),
    ]
